#define rijndael256_ctrle_init_key_iv_T rijndael256_ctrle_init_key_iv_ref
#define rijndael256_ctrle_set_key_T rijndael256_ctrle_set_key_ref
#define rijndael256_ctrle_init_key_ivzero_T rijndael256_ctrle_init_key_ivzero_ref
#define rijndael256_ctrle_seek_T rijndael256_ctrle_seek_ref
#define rijndael256_ctrle_encrypt_nblocks_T rijndael256_ctrle_encrypt_nblocks_ref
#define rijndael256_ctrle_get_bytes_T rijndael256_ctrle_get_bytes_ref

#include "rijndael256_ctrle_generics.impl.h"
